### ISSUE TITLE
 find_prim_host_from_rbd()  went wrong

### ISSUE THREAD

**Issue by zphj1987** [gcharot/ceph-lazy#7]
find_prim_host_from_rbd() 

when pool size is 1  thereis no result

**Comment by gcharot** [comment]
Hello,

Thanks for the report, could you please send an actual example of this. I can't manage to reproduce it.

```
$ ceph osd pool get pool_s1 size
size: 1

$ ceph-lazy rbd-host pool_s1 rbd_s1
osd01
osd02
osd03
```

Are you sure your RBD image contains data ?

Thanks !

**Comment by zphj1987** [comment]
@gcharot 
i will see it later, and tell the result, thank you ！

**Comment by zphj1987** [comment]
@gcharot 
it because 
osdmaptool  --test-map-object need a pool id  ,so it's not a pool with size 1 , i have a pr,

thank you

**Comment by gcharot** [comment]
Giving pool id to osdmaptool is not mandatory, it's cleaner this way though, i have merged your PR.

Thanks !
